// Mocks generated by Mockito 5.4.6 from annotations
// in vendora/test/property_tests/cart_logic_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:vendora/core/data/repositories/cart_repository.dart' as _i3;
import 'package:vendora/core/errors/failures.dart' as _i5;
import 'package:vendora/models/cart_item_model.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ICartRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockICartRepository extends _i1.Mock implements _i3.ICartRepository {
  MockICartRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.CartItem>>> getCartItems(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCartItems,
          [userId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.CartItem>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.CartItem>>(
          this,
          Invocation.method(
            #getCartItems,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.CartItem>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.CartItem>> addCartItem({
    required String? userId,
    required String? productId,
    required int? quantity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCartItem,
          [],
          {
            #userId: userId,
            #productId: productId,
            #quantity: quantity,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.CartItem>>.value(
            _FakeEither_0<_i5.Failure, _i6.CartItem>(
          this,
          Invocation.method(
            #addCartItem,
            [],
            {
              #userId: userId,
              #productId: productId,
              #quantity: quantity,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.CartItem>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.CartItem>> updateCartItem({
    required String? cartItemId,
    required int? quantity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCartItem,
          [],
          {
            #cartItemId: cartItemId,
            #quantity: quantity,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.CartItem>>.value(
            _FakeEither_0<_i5.Failure, _i6.CartItem>(
          this,
          Invocation.method(
            #updateCartItem,
            [],
            {
              #cartItemId: cartItemId,
              #quantity: quantity,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.CartItem>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> removeCartItem(
          String? cartItemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeCartItem,
          [cartItemId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #removeCartItem,
            [cartItemId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> clearCart(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearCart,
          [userId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #clearCart,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, double>> getCartTotal(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCartTotal,
          [userId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, double>>.value(
            _FakeEither_0<_i5.Failure, double>(
          this,
          Invocation.method(
            #getCartTotal,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, double>>);
}
