import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:vendora/features/buyer/presentation/providers/address_provider.dart';
import 'package:vendora/features/buyer/presentation/providers/auth_provider.dart';
import 'package:vendora/features/common/widgets/location_picker.dart';
import '../../../../models/address.dart';

class AddEditAddressScreen extends StatefulWidget {
  final Address? address;

  const AddEditAddressScreen({super.key, this.address});

  @override
  State<AddEditAddressScreen> createState() => _AddEditAddressScreenState();
}

class _AddEditAddressScreenState extends State<AddEditAddressScreen> {
  final _formKey = GlobalKey<FormState>();
  
  late TextEditingController _labelController;
  late TextEditingController _addressTextController;
  late double? _latitude;
  late double? _longitude;
  bool _isDefault = false;

  @override
  void initState() {
    super.initState();
    _labelController = TextEditingController(text: widget.address?.label ?? 'Home');
    _addressTextController = TextEditingController(text: widget.address?.addressText);
    _latitude = widget.address?.latitude;
    _longitude = widget.address?.longitude;
    _isDefault = widget.address?.isDefault ?? false;
  }

  @override
  void dispose() {
    _labelController.dispose();
    _addressTextController.dispose();
    super.dispose();
  }

  void _saveAddress() async {
    if (_formKey.currentState!.validate()) {
      if (_latitude == null || _longitude == null) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Please select a location on the map')),
        );
        return;
      }

      final userId = context.read<AuthProvider>().user?.id;
      if (userId == null) return;

      final addressProvider = context.read<AddressProvider>();
      
      try {
        if (widget.address != null) {
          // Update
          final updatedAddress = widget.address!.copyWith(
            label: _labelController.text.trim(),
            addressText: _addressTextController.text.trim(),
            latitude: _latitude,
            longitude: _longitude,
            isDefault: _isDefault,
          );
          await addressProvider.updateAddress(updatedAddress);
        } else {
          // Add
          final newAddress = Address(
            id: '', // Generated by DB
            userId: userId,
            label: _labelController.text.trim(),
            addressText: _addressTextController.text.trim(),
            latitude: _latitude!,
            longitude: _longitude!,
            isDefault: _isDefault,
            createdAt: DateTime.now(),
          );
          await addressProvider.addAddress(newAddress);
        }
        
        if (mounted) Navigator.pop(context);
      } catch (e) {
        if (mounted) {
           ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('Error: $e')),
          );
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.address != null ? 'Edit Address' : 'Add Address'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            children: [
              TextFormField(
                controller: _labelController,
                decoration: const InputDecoration(
                  labelText: 'Label (e.g., Home, Work)',
                  border: OutlineInputBorder(),
                ),
                validator: (value) =>
                    value?.isEmpty == true ? 'Please enter a label' : null,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _addressTextController,
                decoration: const InputDecoration(
                  labelText: 'Full Address',
                  border: OutlineInputBorder(),
                ),
                maxLines: 3,
                validator: (value) =>
                    value?.isEmpty == true ? 'Please enter address' : null,
              ),
              const SizedBox(height: 16),
              // Location Picker Button
              Card(
                elevation: 0,
                color: Colors.grey[100],
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(8),
                  side: BorderSide(color: Colors.grey.shade300),
                ),
                child: ListTile(
                  leading: const Icon(Icons.map),
                  title: Text(
                    _latitude != null
                        ? 'Location Selected'
                        : 'Select Location on Map',
                    style: TextStyle(
                      color: _latitude != null ? Colors.green : Colors.black,
                      fontWeight: _latitude != null ? FontWeight.bold : FontWeight.normal,
                    ),
                  ),
                  subtitle: _latitude != null
                      ? Text('Lat: $_latitude, Lng: $_longitude')
                      : null,
                  trailing: const Icon(Icons.arrow_forward_ios, size: 16),
                  onTap: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (context) => Scaffold(
                          appBar: AppBar(title: const Text('Pick Location')),
                          body: LocationPicker(
                            initialLatitude: _latitude ?? 51.509364,
                            initialLongitude: _longitude ?? -0.128928,
                            onLocationPicked: (lat, lng) {
                              setState(() {
                                _latitude = lat;
                                _longitude = lng;
                              });
                            },
                          ),
                        ),
                      ),
                    );
                  },
                ),
              ),
              const SizedBox(height: 16),
              SwitchListTile(
                title: const Text('Set as Default Address'),
                value: _isDefault,
                onChanged: (val) => setState(() => _isDefault = val),
              ),
              const SizedBox(height: 24),
              SizedBox(
                width: double.infinity,
                height: 50,
                child: ElevatedButton(
                  onPressed: context.watch<AddressProvider>().isLoading
                      ? null
                      : _saveAddress,
                  style: ElevatedButton.styleFrom(
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(12)),
                  ),
                  child: context.watch<AddressProvider>().isLoading
                      ? const CircularProgressIndicator()
                      : const Text('Save Address'),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
