import 'package:flutter/material.dart';
import '../../../../core/data/repositories/cart_repository.dart';
import '../../../../core/data/repositories/order_repository.dart';
import '../../../../core/errors/failures.dart';
import '../../../../models/address.dart';
import '../../../../models/order.dart';
import '../../../../models/cart_item_model.dart';

class CheckoutProvider extends ChangeNotifier {
  final IOrderRepository _orderRepository;
  final ICartRepository _cartRepository;

  bool _isLoading = false;
  String? _error;
  String _paymentMethod = 'Cash on Delivery'; 
  
  // Payment methods
  static const List<String> paymentMethods = [
    'Cash on Delivery',
    'JazzCash',
    'Online Send',
  ];

  CheckoutProvider({
    required IOrderRepository orderRepository,
    required ICartRepository cartRepository,
  })  : _orderRepository = orderRepository,
        _cartRepository = cartRepository;

  bool get isLoading => _isLoading;
  String? get error => _error;
  String get paymentMethod => _paymentMethod;

  void setPaymentMethod(String method) {
    _paymentMethod = method;
    notifyListeners();
  }

  Future<Order?> placeOrder({
    required String userId,
    required Address address,
    required List<CartItem> cartItems,
    String? paymentProofUrl,
  }) async {
    if (cartItems.isEmpty) {
      _error = 'Cart is empty';
      notifyListeners();
      return null;
    }

    _isLoading = true;
    _error = null;
    notifyListeners();

    // Map CartItems to OrderItems
    // Now CartItem has sellerId, so we can correctly map it
    final orderItems = cartItems.map((cartItem) {
        return OrderItem(
          id: '', // Will be generated by DB/Ignored by Repo on create
          orderId: '', // Will be assigned by repository
          productId: cartItem.productId,
          productName: cartItem.productName,
          quantity: cartItem.quantity,
          unitPrice: cartItem.unitPrice,
          totalPrice: cartItem.total,
          sellerId: cartItem.sellerId,
        );
    }).toList();
    
    final result = await _orderRepository.createOrder(
      userId: userId,
      addressId: address.id,
      items: orderItems,
      paymentMethod: _paymentMethod,
      paymentProofUrl: paymentProofUrl,
    );

    Order? createdOrder;

    await result.fold(
      (failure) async {
        _error = failure is ServerFailure ? failure.message : 'Failed to place order';
        _isLoading = false;
        notifyListeners();
      },
      (order) async {
        createdOrder = order;
        // Clear cart on success
        await _cartRepository.clearCart(userId);
        _isLoading = false;
        notifyListeners();
      },
    );

    return createdOrder;
  }
}
